version: '3.8'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - /vendor
  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer/Dockerfile
    volumes:
      - ./:/var/www/html